alert("please help mycrosoft")
alert("are you ready?")
alert("ok helping...")
alert("help is completed")
console.log("hahaha im hack you")
console.log(10)
console.log(9)
console.log(8)
console.log(7)
console.log(6)
console.log(5)
console.log(4)
console.log(3)
console.log(2)
console.log(1)
console.log("hacking...")
console.log("goodbye🤣🤣")
