let date = new date();
let year = date.getfullyear();
let month = date.getmounht();
let day = date.getday();
let dayOFweek = date.getday();
let hour = date.gethour();
let minute = date.getminute();
let second = date.getsecond();
let millisecond = date.getmilliseconds();
